
name: Export Game

on:
  push:
    branches:
      - main
      - feature/export

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: export game
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.5-stable/Godot_v4.5-stable_export_templates.tpz
          relative_project_path: ./
          presets_to_export: "Windows Desktop,Linux,macOS"
          archive_output: true

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: ${{ steps.export.outputs.archive_directory }}
