name: Export Game

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: export game
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.5-stable/Godot_v4.5-stable_export_templates.tpz
          relative_project_path: ./
          presets_to_export: "Windows Desktop,Linux,macOS,Web"
          archive_output: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.export.outputs.build_directory }}/Web
          publish_branch: gh-pages

      - name: Generate changelog and create release
        run: bun x changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.export.outputs.archive_directory }}/*.zip

      - name: Send changelog to Discord
        if: startsWith(github.ref, 'refs/tags/')
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "🎮 Nouvelle version de Totemidle : ${{ github.ref_name }}"
          url: ${{ github.event.release.html_url }}
          content: "Pour tester le jeu, cliquez ici : https://kayno0o.github.io/gwj-86-godot/index.html"
          color: 0x5865F2
          username: "Totemidle Releases"
